### ISSUE TITLE
How to install causal conv1d and mamba-ssm

### ISSUE THREAD

**Issue by shandongpengyuyan** [Atik-Ahamed/TimeMachine#1]
How to install causal conv1d and mamba-sms

**Comment by Leopold2333** [comment]
> How to install causal conv1d and mamba-sms

Try it on Linux..... 
```
conda create -n your_env_name python=3.10.13
conda activate your_env_name
conda install cudatoolkit==11.8 -c nvidia
pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-nvcc
conda install packaging
pip install causal-conv1d==1.2.0.post1
pip install mamba-ssm==1.2.0.post1
```

**Comment by yjxuestc0919** [comment]
> How to install causal conv1d and mamba-sms

You can follow the official repo of mamba: https://github.com/state-spaces/mamba

**Comment by Atik-Ahamed** [comment]
Thank you @Leopold2333  and @Uestc-Young  for your valuable comments. @shandongpengyuyan, you can try out the instructions provided above depending on your system.
