### ISSUE TITLE
The training time of the model

### ISSUE THREAD

**Issue by Leopold2333** [Atik-Ahamed/TimeMachine#2]
Hi, I recently run the code and the MSE results(and so on) is OK. However, although the model costs relatively low gpu memory, its training speed is really really slow, have you ever encountered a similar situation? Take Weather_96_96 as an example, TimeMachine costs 380s for one epoch while PatchTST only needs 40s...

**Comment by Jimmy-7664** [comment]
Same here. It seems that the training speed does not show any advantages against PatchTST.

**Comment by Atik-Ahamed** [comment]
Dear @Leopold2333, @Jimmy-7664 ,
Thank you for your interest and your feedback. We appreciate your time running the code and analyzing its performance. Regarding the training time, we have not conducted a direct comparison of training durations as they can indeed be affected by a variety of factors, such as batch size, the hardware in use, etc. In our experience, the scenario you've described has not been observed, with our runs typically completing in approximately 60 seconds per epoch for the case you've mentioned in a single GPU and approximately 6s per epoch with multiple GPUs and higher batch size. However, your observation highlights an important area for future research—optimizing training efficiency. If you would like, please help provide some information about your running platform and/or environment, and experimental configurations (e.g. batch size). We will run the code on different platforms to explore the potential differences.
