### ISSUE TITLE
When I was running the code, I encountered the following problems, could you help me solve them? I used python=3.10, torch=2.0.1,cuda=11.8. Thank you very much          import selective_scan_cuda                   ImportError: /home/hp/miniforge3/envs/mamba/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by Dreamhepeng** [Atik-Ahamed/TimeMachine#3]

**Comment by Atik-Ahamed** [comment]
Thanks for trying our work. This is package related issue. Please refer to these issues to get possible solutions:
1) https://github.com/state-spaces/mamba/issues/254
2) https://github.com/state-spaces/mamba/issues/169
3) https://github.com/state-spaces/mamba/issues/28
4) https://github.com/state-spaces/mamba/issues/217
