### ISSUE TITLE
Nan loss！

### ISSUE THREAD

**Issue by CSyyn** [Atik-Ahamed/TimeMachine#4]
I run the script "sh ./scripts/TimeMachine/weather.sh"，and at the second training epoch, it occured nan training loss problem.
 
![image](https://github.com/Atik-Ahamed/TimeMachine/assets/63851708/18b8a6fd-d9b2-4fc7-9cb1-ffb741864aa8)

I print the per step loss, can you help me solve this problem?
 
[TimeMachine_weather_96_96_128_16_0.1_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/14902396/TimeMachine_weather_96_96_128_16_0.1_1_1_256_2_1.log)

**Comment by Atik-Ahamed** [comment]
Dear @CSyyn,
Thank you for trying our work. 
Can you please refer to this issue: https://github.com/state-spaces/mamba/issues/72. It might be helpful.
Or, maybe there is some issue with your installation?
As a matter of fact, we did not encounter this issue in our experiments. 
Also, if you could provide more information regarding your platform (GPU environment), it would be better to locate the issue.

**Comment by faceWelcome** [comment]
Error reported during installation of package mamba ssm:
![{A4D85A96-6836-45de-938E-18CCAC9EB1B5}](https://github.com/Atik-Ahamed/TimeMachine/assets/153884629/c2627c58-8bd6-457f-8d31-d39abb47bf1b)
May I ask how to solve this problem?

**Comment by Atik-Ahamed** [comment]
Hi @faceWelcome,
Thanks for trying our work. Please try: pip install packaging
