### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by hbwzj** [Atik-Ahamed/TimeMachine#7]
为什么这个代码运行的很慢了，是原本就这样吗？

**Comment by shandongpengyuyan** [comment]
我跑起来也很慢

**Comment by Atik-Ahamed** [comment]
Please see the following link: https://github.com/Atik-Ahamed/TimeMachine/issues/2#issuecomment-2035637516.
If possible please provide your machine configuration, so we can try to figure out what has happened in your case.

**Comment by hbwzj** [comment]
> 请参阅以下链接：[#2（评论）。](https://github.com/Atik-Ahamed/TimeMachine/issues/2#issuecomment-2035637516)如果可能，请提供您的机器配置，以便我们尝试弄清楚您的情况。

rtx4060 8g，但只运行了ETTh1，我认为是足够的，但是我给代码打断点确实一直在输出维度变化，可是等了好久epoch结果不出来，是哪里出问题了吗？

**Comment by Atik-Ahamed** [comment]
Thanks for mentioning more details. It seems that you are trying to debug with break-points? Can you please try without break-points and direct run? Please let us know, what happens with direct running the code.

**Comment by hbwzj** [comment]
> 感谢您提及更多细节。您似乎正在尝试使用断点进行调试？你能试试没有断点和直接运行吗？请告诉我们，直接运行代码会发生什么。

我的意思是直接运行一个epoch要很久，我不知道多久，然后我去试试断点输出，在out后面加了断点发现有输出。然而就是一个epoch的结果要很久。我想知道你们那边输出一个epoch结果要多久

**Comment by hbwzj** [comment]
> 感谢您提及更多细节。您似乎正在尝试使用断点进行调试？你能试试没有断点和直接运行吗？请告诉我们，直接运行代码会发生什么。
<img width="800" alt="1716915259104" src="https://github.com/Atik-Ahamed/TimeMachine/assets/153514268/cd6315df-d6d6-4d07-bbda-978b9c4b7379">
<img width="712" alt="1716915342908" src="https://github.com/Atik-Ahamed/TimeMachine/assets/153514268/82b33c76-2856-4477-b39e-73a5546cfa55">
peng朋友您看一直不出结果

**Comment by Atik-Ahamed** [comment]
Regarding time it may be affected by a variety of factors, such as batch size, the hardware in use, etc. As an example, you may see for ETTh1, 96-96 case it takes around 4-5 seconds per epoch.
[TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15499956/TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log)

**Comment by hbwzj** [comment]
好的，谢谢。我再去看看
